/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/suru3d/sur_madeira_1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Sur(props) {
  const { nodes, materials } = useGLTF('./suru3d/sur_madeira_1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh rotation-x={Math.PI/2} rotation-y={Math.PI/2} position={[props.x, .25, 0]} geometry={nodes.Sur.geometry} material={materials.Madeira_Image_Texture} scale={0.01} />
    </group>
  )
}

useGLTF.preload('./suru3d/sur_madeira_1.glb')
